apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: conversor-temperatura-hpa
  namespace: conversao-temperatura
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: conversor-temperatura-deploy
  minReplicas: 1
  maxReplicas: 10
  metric:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageValue: 50
